### ISSUE TITLE
Example doesn't run

### ISSUE THREAD

**Issue by justinmoon** [sw-yx/ssg#13]
```npm run dev

> example-rollup@0.0.1 dev /home/justin/dev/blog
> ssg dev

SSGDEBUG ssgconfig ssg.config.js
> ssgConfig file ssg.config.js missing
Error: ssgConfig file ssg.config.js missing
    at readSSGConfig (/home/justin/dev/blog/node_modules/ssg/dist/cli-ssg.js:24:15)
    at /home/justin/dev/blog/node_modules/ssg/dist/cli.js:82:27
    at Generator.next (<anonymous>)
    at fulfilled (/home/justin/dev/blog/node_modules/ssg/dist/cli.js:5:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example-rollup@0.0.1 dev: `ssg dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example-rollup@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/justin/.npm/_logs/2020-01-13T02_32_31_535Z-debug.log```

**Comment by swyxio** [comment]
acknowledged and will look at this tonight

**Comment by swyxio** [comment]
hey! so its a bit unlikely but i think you may have an old version of ssg? i recall this error was from an old version. also i have a hard dependency on having `src/routes/index.svelte`, i should prob document that better.

i put together this demo which should show how it should work: https://github.com/sw-yx/ssg-demo

**Comment by justinmoon** [comment]
Looks like that was the problem:

```
$ npx ssg --version
ssg, 0.01
```

New demo works wonderfully.
